### PR TITLE
Use the same sort order for users when resending an invitation.

### PR DESCRIPTION
**Pull request by somexpert**

### CODE REVIEW

**Comment by somexpert** [comment]
ping @ldko, @jason-ellis.

**Comment by somexpert** [comment]
this is to keep consistency with how the sorting is on the [original page](https://github.com/unt-libraries/django-invite/blob/master/invite/views.py#L165)

**Comment by ldko** [comment]
Looks ok to me :+1:

**Comment by jason-ellis** [comment]
Looks good to me :+1:

**Pull request merged**
